export default function Head() {
    return (
        <>
        <title>About page</title>
        <meta content="width=device-width, initial-scale=1" name="view" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </>
    )
}





